name: ci-cd

defaults:
  run:
    working-directory: functions

on: ['push']

jobs:
  cicd:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Download dependencies
        run: npm install
      - name: Build application
        run: npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ps
