name: ci-cd

defaults:
  run:
    working-directory: functions

on: ["push"]

jobs:
  cicd:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Download dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Test
        run: npm run test

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        # if: success() && github.ref == 'refs/heads/main'
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          PROJECT_ID: ps
